# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MzYyNjQzOTY4YmE2OTc1ZmU4Y2IwYjM1NTMyNWJhOTA5YjY2MjA4ZTE4M2VjMjcyOGNiYWUwOGFmNjcwNzQzNzUxZGFhYTg3ZmZhZmI4OGQyYWYyODU5MTVlMjNlODg1NzEwNjFlOTZiYzUxMTcxODU2MWQ4ODQ1NDYxMjMxYTM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
